// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo-VHjdvTiBTkyNpRExW5Cw0vIt9LrPyE',
    appId: '1:643895439317:web:71742486288f8ecb2dd75c',
    messagingSenderId: '643895439317',
    projectId: 'sizeyoho',
    authDomain: 'sizeyoho.firebaseapp.com',
    storageBucket: 'sizeyoho.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrT0ITU2etOAxIjbISah851SUJQ33G76c',
    appId: '1:643895439317:android:3cbf0675dd19735d2dd75c',
    messagingSenderId: '643895439317',
    projectId: 'sizeyoho',
    storageBucket: 'sizeyoho.firebasestorage.app',
  );

  /// iOS release values are intentionally supplied outside Git.
  ///
  /// Create the ignored `config/ios.firebase.json` from the iOS app registered
  /// in Firebase, then pass it with `--dart-define-from-file`. This prevents a
  /// newly issued API key from being committed while still letting Windows and
  /// macOS use the same build command.
  static FirebaseOptions get ios {
    const apiKey = String.fromEnvironment('FIREBASE_IOS_API_KEY');
    const appId = String.fromEnvironment('FIREBASE_IOS_APP_ID');
    const messagingSenderId = String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
    );
    const projectId = String.fromEnvironment('FIREBASE_PROJECT_ID');
    const storageBucket = String.fromEnvironment('FIREBASE_STORAGE_BUCKET');
    const iosBundleId = String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID');

    const values = <String>[
      apiKey,
      appId,
      messagingSenderId,
      projectId,
      storageBucket,
      iosBundleId,
    ];
    if (values.any((value) => value.isEmpty)) {
      throw UnsupportedError(
        'iOS Firebase settings are missing. Build with '
        '--dart-define-from-file=config/ios.firebase.json.',
      );
    }

    return const FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: messagingSenderId,
      projectId: projectId,
      storageBucket: storageBucket,
      iosBundleId: iosBundleId,
    );
  }
}
